export const Media = [
    {type:'video', url: require('./video-01.mp4')},
    {type: 'image', url: require('./img-01.png')},
    {type: 'image', url: require('./img-02.png')},
    {type: 'image', url: require('./img-03.png')},
    {type: 'image', url: require('./img-04.png')},
    {type: 'image', url: require('./img-05.png')},
    {type: 'image', url: require('./img-06.png')},
    {type: 'image', url: require('./img-07.png')},
    {type: 'image', url: require('./img-08.png')},
    {type: 'image', url: require('./img-09.png')},
    {type: 'image', url: require('./img-10.png')},
    {type: 'image', url: require('./img-11.jpg')},
    {type: 'image', url: require('./img-12.jpg')},
    {type: 'image', url: require('./img-13.jpg')},
    {type: 'image', url: require('./img-14.jpg')},
    {type: 'image', url: require('./img-15.jpg')},
    {type: 'image', url: require('./img-16.jpg')},
    {type: 'image', url: require('./img-17.jpg')},
    {type: 'image', url: require('./img-18.jpg')},
    {type: 'image', url: require('./img-19.jpg')},
    {type: 'image', url: require('./img-20.png')},
    {type: 'image', url: require('./img-21.png')},
    {type: 'image', url: require('./img-22.png')},
    {type: 'image', url: require('./img-23.png')},
    {type: 'image', url: require('./img-24.jpg')},
    {type: 'image', url: require('./img-25.jpg')},
   
]